camera:
  quality: 0.7 # Quality of the image (0.0 - 1.0)
  fps: 20 # Max FPS 30

audio:
  mode: "tts" # Options: "wav", "mp3" or "tts"
  enabled: true

microphone:
  wake_word: "robot"

# Controls debug message logging
debug_logging: true # Set to true to enable debug logs